name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Optional: Cache pip dependencies if you use them in a Python project
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Build APK with Buildozer Docker
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/home/user/hostcwd" \
          -w /home/user/hostcwd \
          ghcr.io/kivy/buildozer:latest \
          android debug
