name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.0
        components: |
          platform-tools
          build-tools;33.0.0
          platform;android-33

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk python3-pip build-essential \
          libssl-dev zlib1g-dev libffi-dev libsqlite3-dev curl git \
          libncurses5-dev liblzma-dev libbz2-dev pkg-config unzip
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Build APK
      run: buildozer android debug

    - name: List APK(s)
      run: ls -R bin/
