name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Accept Android SDK licenses
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/home/user/hostcwd" \
            -w /home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            sdkmanager --licenses <<< y

      - name: Build APK with Buildozer Docker (no artifact)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/home/user/hostcwd" \
            -w /home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            buildozer android debug
