name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            python3-pip \
            build-essential \
            libssl-dev \
            zlib1g-dev \
            libffi-dev \
            libsqlite3-dev \
            curl \
            git \
            libncurses5 \
            libncurses5-dev \
            liblzma-dev \
            libbz2-dev \
            pkg-config

          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Build APK with Buildozer
        run: |
          buildozer android clean
          buildozer android debug

      - name: List build output files for debugging
        run: ls -l ${{ github.workspace }}/bin/

#      - name: Upload APK (skipped to avoid errors)
#        uses: actions/upload-artifact@v3
#        with:
#          name: SpotifyLikedPlaylist.apk
#          path: bin/*.apk
