name: build-apk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current user UID
        id: get_uid
        run: echo "uid=$(id -u)" >> $GITHUB_OUTPUT

      - name: Build APK with Buildozer Docker
        run: |
          docker run --rm \
            --user ${{ steps.get_uid.outputs.uid }} \
            -v "${{ github.workspace }}:/home/user/app" \
            -w /home/user/app \
            ghcr.io/kivy/buildozer:latest \
            android debug
