name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build APK with Buildozer Docker (non-root)
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/home/buildozer/app \
            kivy/buildozer \
            android debug

      - name: List APK files for debugging
        run: ls -l bin/
