name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build APK using Buildozer in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/app \
            -w /home/user/app \
            ghcr.io/kivy/buildozer:latest \
            bash -c "pip install buildozer && buildozer android debug"
