name: Build Android APK with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build APK using Docker container
        run: |
          docker build -t buildozer-android .
          docker run --rm -v ${{ github.workspace }}:/home/buildozer/app buildozer-android

      - name: List APK files
        run: ls -R bin/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: SpotifyLikedPlaylist-apk
          path: bin/*.apk
