name: Build Android APK with Docker and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t buildozer-android .

      - name: Run Docker container to build APK
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/buildozer/app buildozer-android

      - name: List APK files
        run: ls -R bin/

      - name: Compress APK
        run: zip -r app-release.zip bin/

      - name: Create GitHub Release and upload APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          gh release create "$TAG" app-release.zip --title "$TAG" --notes "Automated APK build"

      - name: Show Release URL
        run: gh release view --json url -q .url
