name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fix workspace permissions for Docker user
        run: sudo chown -R 1000:1000 ${{ github.workspace }}

      - name: Run Buildozer Docker container to build APK
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/buildozer/app \
            buildozer-android

      - name: List build output directory
        run: ls -R ${{ github.workspace }}/bin/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: SpotifyLikedPlaylist.apk
          path: bin/*.apk
