name: build-apk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK with Buildozer Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/home/user/app" \
            -w /home/user/app \
            --user root \
            ghcr.io/kivy/buildozer:latest \
            android debug
