name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Buildozer in Docker
        run: |
          docker run --rm \
            -u 0 \
            -v "${{ github.workspace }}:/home/user/hostcwd" \
            -w /home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            python3 -m buildozer android debug
