name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            python3-pip \
            build-essential \
            libssl-dev \
            zlib1g-dev \
            libffi-dev \
            libsqlite3-dev \
            curl \
            git \
            libncurses5 \
            libncurses5-dev \
            libffi-dev \
            liblzma-dev \
            libbz2-dev \
            pkg-config

          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Build APK with Buildozer
        run: |
          buildozer android debug --verbose

      - name: Debug APK directory
        run: ls -R bin/

      # Note: artifact upload is optional and can be removed if not needed
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: SpotifyLikedPlaylist.apk
          path: bin/*.apk
