name: Build Android APK with Buildozer Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildozer environment and build APK
        run: |
          # Make sure current user owns all files for mounting
          sudo chown -R $USER:$USER ${{ github.workspace }}

          docker run --rm \
            -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/home/buildozer/app \
            pycontribs/buildozer \
            android debug

      - name: List build output files for debugging
        run: ls -l ${{ github.workspace }}/bin/

      - name: Upload APK (if generated)
        uses: actions/upload-artifact@v3
        with:
          name: SpotifyLikedPlaylist.apk
          path: bin/*.apk
