name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK with Buildozer Docker container
        run: |
          docker run --rm \
            -u 0 \
            -v "${{ github.workspace }}:/home/user/hostcwd" \
            -w /home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            python3 -m buildozer android debug
