name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildozer Environment
        run: |
          docker pull kivy/buildozer:latest || true

      - name: Fix permissions
        run: sudo chmod -R a+rw ${{ github.workspace }}

      - name: Build APK with Buildozer Docker
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/home/buildozer/app \
            -w /home/buildozer/app \
            kivy/buildozer:latest \
            buildozer android debug

      - name: Show build output folder
        run: ls -R bin/

