name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fix permissions
        run: sudo chmod -R a+rw ${{ github.workspace }}

      - name: Build APK with Buildozer Docker (GHCR mirror)
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/home/buildozer/app \
            -w /home/buildozer/app \
            ghcr.io/kivy/buildozer \
            buildozer android debug

      - name: List output files
        run: ls -R bin/
